### ISSUE TITLE
Why not use RWMutex instead of Mutex?

### ISSUE THREAD

**Issue by conndots** [AndreasBriese/bbloom#2]
Is there a reason for it?

**Comment by AndreasBriese** [comment]
The code is somewhat older and there was a time RWMutex’s weren’t always save to use (golang 1.4 ??) and kind of unpredictable.
Have you tested the package with RWMutex successfully?

Andreas


Am 16.09.2017 um 16:41 schrieb Xiangqian Lee <notifications@github.com>:

**Comment by conndots** [comment]
I'm trying to use it in my project. Later I will reply the feedbacks.
