### ISSUE TITLE
Use of unsafe is unsound

### ISSUE THREAD

**Issue by Stebalien** [AndreasBriese/bbloom#9]
Casting to a `uintptr`, saving the `uintptr`, and then casting it back is unsound.

https://github.com/AndreasBriese/bbloom/blob/e2d15f34fcf99d5dbb871c820ec73f710fca9815/bbloom.go#L80-L88

https://github.com/AndreasBriese/bbloom/blob/e2d15f34fcf99d5dbb871c820ec73f710fca9815/bbloom.go#L232-L246

**Comment by AndreasBriese** [comment]
What do you mean by unsound? 
Pls give a working code example that does not use the unsafe pointer.
Andreas

**Comment by Stebalien** [comment]
I'm saying that converting a `uintptr` back to a `unsafe.Pointer` across multiple statements is unsound.

https://golang.org/pkg/unsafe/#Pointer

**Comment by AndreasBriese** [comment]
Hey Steve,

the ptr is not carried around multiple statements. the ptr is locally casted, incremented and changed by a bitoperation. This behaviour is not volatile at runtime - at least not in the golang binary. 

Anyway - when bbloom was written in 2015 i guess the math/bits package was not part of the standard library (came 2017/18 ? from the guys working on math64 and integer ssa ... implementation?).  Maybe it is a good idea to go for the for the present standard library and following your suggestion. 
I will look into it and will replace unsafe use, where it is suitable without performance loss.
If you have changed the API maybe you should remaster your code with a different name i.e bbbloom ?

Andreas

**Comment by Stebalien** [comment]
> the ptr is not carried around multiple statements. the ptr is locally casted, incremented and changed by a bitoperation. This behaviour is not volatile at runtime - at least not in the golang binary.

Take a look at the functions I'm quoting in the issue description. You can't save a uintptr to the stack then convert it back to an `unsafe.Pointer` later.

Take the JSONMarshal function. The garbage collector is allowed to pause the function between lines 236 and 238, move anything it wants, update the pointers, then restart the function. At that point, the saved `uintptr` could be pointing at _anything_.

**Comment by AndreasBriese** [comment]
... p.s. look at (3) here https://golang.org/pkg/unsafe/#Pointer <https://golang.org/pkg/unsafe/#Pointer>

**Comment by Stebalien** [comment]
That's _exactly_ what I'm looking at:


<blockquote>
Note that both conversions must appear in the same expression, with only the intervening arithmetic between them:

<pre>
// INVALID: uintptr cannot be stored in variable
// before conversion back to Pointer.
u := uintptr(p)
p = unsafe.Pointer(u + offset)
</pre>
</blockquote>

**Comment by AndreasBriese** [comment]
I considered Your comments and opted for the way documented at  https://golang.org/pkg/unsafe/#Pointer 
in the latest push. 
https://github.com/AndreasBriese/bbloom/commit/5f4d56d674c24417406771d7d1756c70d33398e3#diff-eebbf48a54279308068f73108bc90f16
Thx for discussing this thoroughly. That should solve the issues you pointed at.
Andreas

**Comment by Stebalien** [comment]
That looks safe. Thanks!
